title: Service Analytics Guide
description: Draft document for service analytics
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
  "Edit on Github":
    - "//github.com/bcgov/service-analytics-guide"
